### ISSUE TITLE
Cannot run example (with or without G2O)

### ISSUE THREAD

**Issue by kplayer** [uzh-rpg/rpg_svo#11]
I followed the instructions and everything seemed to compile correctly (also G2O). I am running Ubuntu 12.04 and ROS Hydro. When I run the example with HAVE_G2O FALSE in CMakeLists.txt, I get:

> "roslaunch svo_ros test_rig3.launch"
> [...]
> [ WARN] [1402480296.121485241]: Cannot find value for parameter: svo/quality_max_drop_fts, assigning default: 40
> [ INFO] [1402480296.121617539]: SVO initialized
> vo: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:69: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array() [with T = double, int Size = 4, int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/TopicUnalignedArrayAssert.html" " ***\* READ THIS WEB PAGE !!! ****"' failed.
> [svo-1] process has died [pid 20700, exit code -6

Not sure what is going on here...

Running the same thing with HAVE_G2O TRUE results in: 
[...]
core service [/rosout] found
process[svo-1]: started with pid [23552]
/home/ketill/robotics/rosbook/devel/lib/svo_ros/vo: error while loading shared libraries: libg2o_core.so: cannot open shared object file: No such file or directory
[svo-1] process has died [pid 23552, exit code 127

Why is it not finding the shared library? How can I fix it?
Thanks for any help or tips!

**Comment by xuchong** [comment]
@cfo @kplayer 
I add EIGEN_MAKE_ALIGNED_OPERATOR_NEW accordding to above(git diff). Still get same errors.
[/usr/include/eigen3/Eigen/src/Core/DenseStorage.h:78:

Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 16>::plain_array()

[with T = double; int Size = 4; int MatrixOrArrayOptions = 0]:

Assertion `(reinterpret_cast<size_t>(eigen_unaligned_array_assert_workaround_gcc47(array)) & 0xf) == 0 &&
"this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"'

failed.](url)

Then i used the method as you told: 
 add launch-prefix="gdb -ex run --args" to the <node /> tag. Then type bt, i got this:
(gdb) 
#0  0xb7fdccf9 in ?? ()
#1  0xb7ebf3c6 in svo::DepthFilter::updateSeedsLoop() ()
   from /home/xc/project/devel/lib/libsvo.so
#2  0xb7ec102b in boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf0<void, svo::DepthFilter>, boost::_bi::list1<boost::_bi::value<svo::DepthFilter*> > > >::run() () from /home/xc/project/devel/lib/libsvo.so
#3  0xb717d681 in ?? () from /usr/lib/i386-linux-gnu/libboost_thread.so.1.54.0
#4  0xb7406f72 in start_thread (arg=0xadbfeb40) at pthread_create.c:312
#5  0xb7875f8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
(gdb) 

What's wrong?
