### ISSUE TITLE
Parameters and their meanings?

### ISSUE THREAD

**Issue by Wholemeal** [uzh-rpg/rpg_svo#118]
There are many paramters in SVO that are set to default, looking through the code there appears to be no documentation on what these numbers mean. Could we use this thread as a jumping off point to add to the wiki? I particularly would like to know what the loba threshold does.

**Comment by cfo** [comment]
Here you find a short description of all parameters:
https://github.com/uzh-rpg/rpg_svo/blob/master/svo/include/svo/config.h

**Comment by Wholemeal** [comment]
Oh, my mistake, I swore I grep-ed through the source.
