### ISSUE TITLE
Position estimation /svo/pose does not match with Ground Truth - Live camera feed

### ISSUE THREAD

**Issue by VishnuDuttSharma** [uzh-rpg/rpg_svo#151]
Hi,
I am trying to run SVO with live input from SJCam SJ4000. The position that I get from `/svo/pose` does not match with the real position. The movement in z-direction is reported faster and thus gives higher value of altitude than actual one. What may be the problem here?

**Comment by VishnuDuttSharma** [comment]
The issue lied with map-scale according to the camera and the parameters in the camera model. After making appropriate changes in them, the problem was solved,

**Comment by hanstayhe** [comment]
@VishnuDuttSharma  Hello, may I know what your camera parameters are?
