### ISSUE TITLE
Rviz No image recieved

### ISSUE THREAD

**Issue by karanchawla** [uzh-rpg/rpg_svo#168]
System: i7 -4720HQ 3.6Ghz
OS: Ubuntu 14.04 LTS with ROS Indigo. 

Everything compiled successfully . (Eventually) And the rosbag example seems to be working fine, i.e. features are getting detected, ros topics are echoing back the data. 

Only thing I can't see is the pose visualization in Rviz or the camera feed. I have attached the screen shots that may provide more information. 

PS I have tried the two fixes that worked for some people here(but didn't work for me): 
_1, Changing the last_image pointer from private to public
2. Resizing the window x and y dimensions in the rviz config file._ 

Thank you. 

![screenshot from 2016-09-24 17 46 56](https://cloud.githubusercontent.com/assets/15241546/18811733/4e7994a0-827f-11e6-8a46-16384670fa51.png)
![screenshot from 2016-09-24 17 47 04](https://cloud.githubusercontent.com/assets/15241546/18811734/4e7c19f0-827f-11e6-9d19-45273e5d565f.png)

**Comment by karanchawla** [comment]
`<launch>

  <node pkg="svo_ros" type="vo" name="svo" clear_params="true" output="screen">

	
	<param name="cam_topic" value="/image_mono" type="str" />
	
	
	<rosparam file="$(find svo_ros)/param/camera_pinhole.yaml" />

	
	<rosparam file="$(find svo_ros)/param/vo_robust.yaml" />
	
	
    <param name="init_rx" value="3.14" />
    <param name="init_ry" value="0.00" />
    <param name="init_rz" value="0.00" />

  </node>

</launch>`

Using this launch script solves the aforementioned problem.

**Comment by Ignotus** [comment]
Hey there, seems like I have the same issue. Where can I find the launch script?
