### ISSUE TITLE
Missing -lboost_system

### ISSUE THREAD

**Issue by vinben** [uzh-rpg/rpg_svo#19]
I follow the instruction to install SVO without ROS under Ubuntu 13.10. I have the following error message when test examples are compiling.

```
[ 71%] Building CXX object CMakeFiles/test_depth_filter.dir/test/test_depth_filter.cpp.o
Linking CXX executable ../bin/test_depth_filter
/usr/bin/ld: CMakeFiles/test_depth_filter.dir/test/test_depth_filter.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
/usr/lib/x86_64-linux-gnu/libboost_system.so.1.53.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

This problem can be fixed by adding a flag 

```
-lboost_system
```

to the end of the link file:

```
/build/CMakeFiles/test_depth_filter.dir/link.txt
```

**Comment by yengin89** [comment]
I have also similar problem:

/usr/bin/ld: CMakeFiles/beginner_tutorials_node.dir/src/beginner_tutorials.cpp.o: undefined reference to symbol '_ZNK6google8protobuf7Message11DebugStringEv'
//usr/lib/x86_64-linux-gnu/libprotobuf.so.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

I add the " -lboost_system " to the and of the link file. But it didn't worked.

**Comment by qilei123** [comment]
@yengin89 Did you resolve it?

**Comment by skywhat** [comment]
how to work it our? Damn, I also came across this one.

/usr/bin/ld: /tmp/ccjSn4OM.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
/usr/local/lib/libboost_system.so.1.64.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by mali-arf** [comment]
Thank you Vinben. Thank you so much. you cannot imagine how much I tried to solve this error, but your solution worked.
I am thankful to you.

Adding -lboost_system flag to the end of the link file really works...... YES
