### ISSUE TITLE
[svo-1] process has died [pid 2709, exit code -11

### ISSUE THREAD

**Issue by chinthaA** [uzh-rpg/rpg_svo#262]
I'm new to ROS and trying to run the SVO and ended up with the following error. I'm using ros melodic in ubuntu 18. I'm trying to run for the example data set provided. Please help me to correct it.

hinthaka@chinthaka-VirtualBox:~$ roslaunch svo_ros test_rig3.launch
... logging to /home/chinthaka/.ros/log/06d84934-4d4c-11ea-8360-08002776c300/roslaunch-chinthaka-VirtualBox-2693.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://chinthaka-VirtualBox:35921/

SUMMARY
========

CLEAR PARAMETERS
 * /svo/

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /svo/cam_cx: 0.45905
 * /svo/cam_cy: 0.510056
 * /svo/cam_d0: 0.932
 * /svo/cam_fx: 0.509326
 * /svo/cam_fy: 0.796651
 * /svo/cam_height: 480
 * /svo/cam_model: ATAN
 * /svo/cam_topic: /camera/image_raw
 * /svo/cam_width: 752
 * /svo/grid_size: 30
 * /svo/init_rx: 3.14
 * /svo/init_ry: 0.0
 * /svo/init_rz: 0.0
 * /svo/loba_num_iter: 0
 * /svo/max_n_kfs: 10

NODES
  /
    svo (svo_ros/vo)

ROS_MASTER_URI=http://localhost:11311

process[svo-1]: started with pid [2709]
create vo_node
[ WARN] [1581480028.515134340]: Cannot find value for parameter: svo/publish_img_pyr_level, assigning default: 0
[ WARN] [1581480028.517829986]: Cannot find value for parameter: svo/publish_every_nth_img, assigning default: 1
[ WARN] [1581480028.518570619]: Cannot find value for parameter: svo/publish_every_nth_dense_input, assigning default: 1
[ WARN] [1581480028.521074302]: Cannot find value for parameter: svo/publish_world_in_cam_frame, assigning default: 1
[ WARN] [1581480028.522286588]: Cannot find value for parameter: svo/publish_map_every_frame, assigning default: 0
[ WARN] [1581480028.523074612]: Cannot find value for parameter: svo/publish_point_display_time, assigning default: 0
[ WARN] [1581480028.688583358]: Cannot find value for parameter: svo/publish_markers, assigning default: 1
[ WARN] [1581480028.689124586]: Cannot find value for parameter: svo/publish_dense_input, assigning default: 0
[ WARN] [1581480028.689539140]: Cannot find value for parameter: svo/accept_console_user_input, assigning default: 1
[ INFO] [1581480028.690255192]: Found parameter: svo/cam_model, value: ATAN
[ INFO] [1581480028.690798839]: Found parameter: svo/cam_width, value: 752
[ INFO] [1581480028.691272774]: Found parameter: svo/cam_height, value: 480
[ INFO] [1581480028.691703212]: Found parameter: svo/cam_fx, value: 0.509326
[ INFO] [1581480028.692213719]: Found parameter: svo/cam_fy, value: 0.796651
[ INFO] [1581480028.692622041]: Found parameter: svo/cam_cx, value: 0.45905
[ INFO] [1581480028.693089482]: Found parameter: svo/cam_cy, value: 0.510056
[ INFO] [1581480028.693493814]: Found parameter: svo/cam_d0, value: 0.932
[ WARN] [1581480028.696580355]: Cannot find value for parameter: svo/init_tz, assigning default: 0
[ WARN] [1581480028.697244516]: Cannot find value for parameter: svo/init_ty, assigning default: 0
[ WARN] [1581480028.698166501]: Cannot find value for parameter: svo/init_tx, assigning default: 0
[ INFO] [1581480028.698729852]: Found parameter: svo/init_rz, value: 0
[ INFO] [1581480028.702915812]: Found parameter: svo/init_ry, value: 0
[ INFO] [1581480028.704740701]: Found parameter: svo/init_rx, value: 3.14
[ WARN] [1581480028.705489481]: Cannot find value for parameter: svo/trace_name, assigning default: svo
[ WARN] [1581480028.706239823]: Cannot find value for parameter: svo/trace_dir, assigning default: /tmp
[ WARN] [1581480028.707494366]: Cannot find value for parameter: svo/n_pyr_levels, assigning default: 3
[ WARN] [1581480028.709314035]: Cannot find value for parameter: svo/use_imu, assigning default: 0
[ WARN] [1581480028.711098155]: Cannot find value for parameter: svo/core_n_kfs, assigning default: 3
[ WARN] [1581480028.712704994]: Cannot find value for parameter: svo/map_scale, assigning default: 1
[ INFO] [1581480028.713328177]: Found parameter: svo/grid_size, value: 30
[ WARN] [1581480028.714013243]: Cannot find value for parameter: svo/init_min_disparity, assigning default: 50
[ WARN] [1581480028.714715292]: Cannot find value for parameter: svo/init_min_tracked, assigning default: 50
[ WARN] [1581480028.715217642]: Cannot find value for parameter: svo/init_min_inliers, assigning default: 40
[ WARN] [1581480028.722901792]: Cannot find value for parameter: svo/klt_max_level, assigning default: 4
[ WARN] [1581480028.724331614]: Cannot find value for parameter: svo/klt_min_level, assigning default: 2
[ WARN] [1581480028.726765750]: Cannot find value for parameter: svo/reproj_thresh, assigning default: 2
[ WARN] [1581480028.727483539]: Cannot find value for parameter: svo/poseoptim_thresh, assigning default: 2
[ WARN] [1581480028.730219782]: Cannot find value for parameter: svo/poseoptim_num_iter, assigning default: 10
[ WARN] [1581480028.731329835]: Cannot find value for parameter: svo/structureoptim_max_pts, assigning default: 20
[ WARN] [1581480028.732051948]: Cannot find value for parameter: svo/structureoptim_num_iter, assigning default: 5
[ WARN] [1581480028.732806080]: Cannot find value for parameter: svo/loba_thresh, assigning default: 2
[ WARN] [1581480028.733428868]: Cannot find value for parameter: svo/loba_robust_huber_width, assigning default: 1
[ INFO] [1581480028.733968578]: Found parameter: svo/loba_num_iter, value: 0
[ WARN] [1581480028.735171804]: Cannot find value for parameter: svo/kfselect_mindist, assigning default: 0.12
[ WARN] [1581480028.735845658]: Cannot find value for parameter: svo/triang_min_corner_score, assigning default: 20
[ WARN] [1581480028.736581763]: Cannot find value for parameter: svo/triang_half_patch_size, assigning default: 4
[ WARN] [1581480028.737245013]: Cannot find value for parameter: svo/subpix_n_iter, assigning default: 10
[ INFO] [1581480028.737665904]: Found parameter: svo/max_n_kfs, value: 10
[ WARN] [1581480028.738438120]: Cannot find value for parameter: svo/img_imu_delay, assigning default: 0
[ WARN] [1581480028.739337535]: Cannot find value for parameter: svo/max_fts, assigning default: 120
[ WARN] [1581480028.740593493]: Cannot find value for parameter: svo/quality_min_fts, assigning default: 50
[ WARN] [1581480028.742242758]: Cannot find value for parameter: svo/quality_max_drop_fts, assigning default: 40
[ INFO] [1581480028.742637505]: SVO initialized
[ INFO] [1581480028.743771336]: Found parameter: svo/cam_topic, value: /camera/image_raw
[ INFO] [1581480073.957182388]: RESET
[ INFO] [1581480073.964286132]: Init: Selected first frame.
[ INFO] [1581480074.027433236]: Init: KLT tracked 149 features
[ INFO] [1581480074.027796883]: Init: KLT 1.88941px average disparity.
[ INFO] [1581480074.047333635]: Init: KLT tracked 149 features
[ INFO] [1581480074.047946159]: Init: KLT 3.91794px average disparity.
[ INFO] [1581480074.062297669]: Init: KLT tracked 149 features
[ INFO] [1581480074.066727690]: Init: KLT 5.90445px average disparity.
[ INFO] [1581480074.083519304]: Init: KLT tracked 149 features
[ INFO] [1581480074.086429714]: Init: KLT 7.9604px average disparity.
[ INFO] [1581480074.109890496]: Init: KLT tracked 149 features
[ INFO] [1581480074.110594243]: Init: KLT 10.0047px average disparity.
[ INFO] [1581480074.130498343]: Init: KLT tracked 149 features
[ INFO] [1581480074.131014430]: Init: KLT 11.8352px average disparity.
[ INFO] [1581480074.155823600]: Init: KLT tracked 149 features
[ INFO] [1581480074.156267532]: Init: KLT 13.8552px average disparity.
[ INFO] [1581480074.183237518]: Init: KLT tracked 149 features
[ INFO] [1581480074.189534257]: Init: KLT 15.9424px average disparity.
[ INFO] [1581480074.219782461]: Init: KLT tracked 149 features
[ INFO] [1581480074.220070417]: Init: KLT 17.801px average disparity.
[ INFO] [1581480074.251092648]: Init: KLT tracked 149 features
[ INFO] [1581480074.255253973]: Init: KLT 19.7476px average disparity.
[ INFO] [1581480074.306229927]: Init: KLT tracked 149 features
[ INFO] [1581480074.309583660]: Init: KLT 22.056px average disparity.
[ INFO] [1581480074.337110437]: Init: KLT tracked 149 features
[ INFO] [1581480074.337453523]: Init: KLT 24.3208px average disparity.
[ INFO] [1581480074.353900217]: Init: KLT tracked 149 features
[ INFO] [1581480074.354459239]: Init: KLT 26.6585px average disparity.
[ INFO] [1581480074.386865703]: Init: KLT tracked 149 features
[ INFO] [1581480074.388871847]: Init: KLT 29.3415px average disparity.
[ INFO] [1581480074.424716176]: Init: KLT tracked 149 features
[ INFO] [1581480074.427008281]: Init: KLT 32.4553px average disparity.
[ INFO] [1581480074.451498691]: Init: KLT tracked 147 features
[ INFO] [1581480074.452042772]: Init: KLT 35.0074px average disparity.
[ INFO] [1581480074.500174268]: Init: KLT tracked 147 features
[ INFO] [1581480074.504019569]: Init: KLT 37.212px average disparity.
[ INFO] [1581480074.527515220]: Init: KLT tracked 147 features
[ INFO] [1581480074.528142452]: Init: KLT 39.0935px average disparity.
[ INFO] [1581480074.563754595]: Init: KLT tracked 147 features
[ INFO] [1581480074.565453457]: Init: KLT 41.0359px average disparity.
[ INFO] [1581480074.597098261]: Init: KLT tracked 147 features
[ INFO] [1581480074.598865943]: Init: KLT 43.2432px average disparity.
[ INFO] [1581480074.627300825]: Init: KLT tracked 147 features
[ INFO] [1581480074.629795131]: Init: KLT 45.2503px average disparity.
[ INFO] [1581480074.663960123]: Init: KLT tracked 146 features
[ INFO] [1581480074.664384233]: Init: KLT 47.631px average disparity.
[ INFO] [1581480074.706929732]: Init: KLT tracked 145 features
[ INFO] [1581480074.710322459]: Init: KLT 49.2348px average disparity.
[ INFO] [1581480074.739384205]: Init: KLT tracked 145 features
[ INFO] [1581480074.739804149]: Init: KLT 50.8822px average disparity.
[ INFO] [1581480074.752684038]: Init: Homography RANSAC 141 inliers.
[svo-1] process has died [pid 2709, exit code -11, cmd /home/chinthaka/catkin_ws/devel/lib/svo_ros/vo __name:=svo __log:=/home/chinthaka/.ros/log/06d84934-4d4c-11ea-8360-08002776c300/svo-1.log].
log file: /home/chinthaka/.ros/log/06d84934-4d4c-11ea-8360-08002776c300/svo-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by faustoTapia** [comment]
Any updates on this problem. I get exactly the same error.

**Comment by zanazakaryaie** [comment]
I also get the same error (ROS Melodic)

**Comment by zanazakaryaie** [comment]
Found the solution. Remove `-march=native` in all CMakeLists.txt files!

**Comment by chinthaA** [comment]
Yes -march=native works. Thanks a ton.

**Comment by zxqhdu** [comment]
@zanazakaryaie it  has sloved my the same problem
