### ISSUE TITLE
SVO and Multiple Sensor Fusion 

### ISSUE THREAD

**Issue by mhkabir** [uzh-rpg/rpg_svo#37]
@cfo I'm confused with regards to getting my MAV working with SVO and the ethzasl-MSF.  I keep getting "fuzzy tracking triggered", which points to my camera-IMU transform being wrong. The parameters "init_rx, init_ry, init_rz" are confusing me.

My IMU is outputting data in ENU. That means (with respect to front of MAV) - X forward, Y left and Z upwards. The camera has its top (top of image frame)pointing forwards. So, I should only be rotated 180 degrees on X axis to rotate the camera frame to IMU frame, right?

So I set "init_rx" to 3.14, which should make the IMU and camera frame converge...? But then there are the parameters in MSF :

```
pose_sensor/init/q_ic/w: 0.0
pose_sensor/init/q_ic/x: 0.0
pose_sensor/init/q_ic/y: 0.0
pose_sensor/init/q_ic/z: 0.0
```

How do I set them properly to reflect my camera-IMU transformation? 

Kabir

**Comment by ghost** [comment]
@mhkabir : Were you able to solve it ? can you provide me the link to your IMU + SVO github. Thank you.
