### ISSUE TITLE
Haven't seen any new features added onto the map

### ISSUE THREAD

**Issue by Fromandto** [uzh-rpg/rpg_svo#49]
I launch the live stream file with the setting as 

grid_size 20
max_n_kfs 0
loba_num_iter 10
max_fts 300

and point the camera (60fps, wide angle, global shutter) at a wall with a lot of portraits hanging on it .

Initialization result is great .

tracking around the initialization location is great too.

But when i move the camera away from the initial location, I cannot see any new feature points added onto the map. New areas are covered with portraits similar to the initial place. 

In the packed bag and video, new feature points are added instantly when the camera translate or move away from the scene.

I wonder if the parameter setting is wrong ? 
max_n_kfs set to 0 means infinite key frame ?

Hope anyone could help me out of this !

**Comment by cssexpert217** [comment]
Hi @Fromandto,

Could you please tell me what changes did you need to make in order to get it working? Thanks
