### ISSUE TITLE
Metric scale estimation in SVO itself 

### ISSUE THREAD

**Issue by mhkabir** [uzh-rpg/rpg_svo#56]
Hi, 

What would be the steps required to use IMU data in SVO itself to do the metric scale estimation? I want to keep the scale estimation separate from the sensor fusion framework as it will allow us to try out different ones and different filters. 

IMU data can also be used for the tracking itself, which should make it more robust. I'd be willing to give this a try if you guys help. 

Kabir

**Comment by mhkabir** [comment]
@cfo Is there anything new on this topic ? :smile:

**Comment by mhkabir** [comment]
@cfo We also did a full SVO flying setup tutorial on the PX4 wiki sometime back : https://pixhawk.org/dev/ros/visual_estimation
Perhaps you could link it in the README for people looking to get a full flying setup with a PX4-based autopilot? 
And any suggestions to the page would be welcome ;)

**Comment by MuhammadUsman90** [comment]
@mhkabir  I tried to use the tutorial you did for using msf for scale estimation and i encountered this error,

`Wanted to insert a value to the sorted container at time 0.000000000 but the map already contained a value at this time. discarding.`

Any help will be appreciated. Thanks

**Comment by yang778** [comment]
@mhkabir @cfo I tried to open the link (https://pixhawk.org/dev/ros/visual_estimation) you offered, but found no topic on that page. Is there any other way to setup svo with msf?

**Comment by Booooooosh** [comment]
@mhkabir  @yang778 Same here, it seems that the topic does not exist any more

**Comment by hamididari** [comment]
@yang778 @Booooooosh you can use web archive to open the link(https://web.archive.org/web/20150327112942/https://pixhawk.org/dev/ros/visual_estimation)

**Comment by deepak-1530** [comment]
@cfo i am currently working on estimating scale for svo using pixhawk. Can you give a link to your code if possible?
