### ISSUE TITLE
What's a ATAN camera model ?

### ISSUE THREAD

**Issue by Fromandto** [uzh-rpg/rpg_svo#57]
This may be stupid, but I really want to know the exact definition of every parameters in a ATAN camera. 

In an ATAN model, fx fy cx cy are all smaller than 1. How could I calculate the values of them under a pixel metric?

What is d0 ? Is it the first order distortion coefficient ?

Is there any paper or document illustrating the model's numerical properties ?

Hope anyone could help, THX in advance !

**Comment by LinHuican** [comment]
Hi @Fromandto, it may be stupid, but I really want to know the ATAN model, What is ATAN short for? Any paper or book talk about it. I just google it, but still confused.
thx in advance!

**Comment by pmoulon** [comment]
atan meaning is arctangent https://en.wikipedia.org/wiki/Inverse_trigonometric_functions
It's inverse mapping like cos->acos, sin->asin...

**Comment by LinHuican** [comment]
Thank you very much!@pmoulon

**Comment by LinHuican** [comment]
Thank you very much! @pmoulon 
But, I just can not understand "ATAN camera model", could you give me link or paper title?
Thanks in advance!

**Comment by RongenC** [comment]
I just came across this page because I am looking for some distortion relation questions. To give you some ideas on the ATAN camera model, it is a cameram distortion equation model, you can take a look at PTAM (https://github.com/Oxford-PTAM/PTAM-GPL) as its camera calibration is based on this modelling. And you should be able to google the actual link/paper about the expansion of such modeling.

**Comment by csukuangfj** [comment]
It was proposed in Equation (13) and (14) of the paper [Straight lines have to be straight](https://hal.inria.fr/inria-00267247/file/distcalib.pdf) 

`x_d = g(r_u)*x_u`
`y_d = g(r_u)*y_u`

where `r_u = sqrt(x_u*x_u + y_u*y_u)`

`g(r) = 1/(w*r)*atan(2*r*tan(w/2))`

w is the filed of view (FOV) in radian.

ATAN model is also called as FOV model. The **advantage** is that if you know `(x_d, y_d)`, you can
get `(x_u, y_u)` analytically and vice versa.

`x_u = f(r_d)*x_d`
`y_u = f(r_d)*y_d`

where `r_d = sqrt(x_d*x_d + y_d*y_d)` and
`f(r) = tan(w*r) / (2*r*tan(w/2))`
