### ISSUE TITLE
Final results

### ISSUE THREAD

**Issue by MuiLe** [uzh-rpg/rpg_svo#82]
Hi Everyone,
There is anyone who succeeds to run (reproduce) this code as the result described on the paper/demo video?
Thanks,

**Comment by cfo** [comment]
the results in the video were obtained with this source code. here are my suggestions to obtain good performance: https://github.com/uzh-rpg/rpg_svo/wiki/Obtaining-Best-Performance

**Comment by MuiLe** [comment]
Hi CFO,
Thank you for your reply. I will try with that.

Regards,
Mui Le
